package tools

import (
	"context"
	"encoding/json"

	"github.com/cloudwego/eino/components/tool"
	"github.com/cloudwego/eino/schema"

	"eino-intern-workflows/internal/domain"
)

// MaterialWorkflowRunner is the minimal runner contract generated by Eino Compile.
type MaterialWorkflowRunner interface {
	Invoke(ctx context.Context, input domain.MaterialCheckInput, opts ...any) (domain.MaterialCheckOutput, error)
}

// MaterialCheckTool exposes Material Check/V2 as an Eino Tool.
// In a real Agent, ChatModel generates ToolCall; ToolsNode executes this Tool.
type MaterialCheckTool struct {
	Runner interface {
		Invoke(ctx context.Context, input domain.MaterialCheckInput) (domain.MaterialCheckOutput, error)
	}
}

func (t *MaterialCheckTool) Info(ctx context.Context) (*schema.ToolInfo, error) {
	return &schema.ToolInfo{
		Name: "material_check_v2",
		Desc: "判断左右商品材质是否相同，并比较材质价值等级。输入 left_material/right_material/category。",
		ParamsOneOf: schema.NewParamsOneOfByParams(map[string]*schema.ParameterInfo{
			"left_material":  {Type: "string", Desc: "左侧商品材质文本"},
			"right_material": {Type: "string", Desc: "右侧商品材质文本"},
			"category":       {Type: "string", Desc: "商品类目，可为空"},
		}),
	}, nil
}

func (t *MaterialCheckTool) InvokableRun(ctx context.Context, argumentsInJSON string, opts ...tool.Option) (string, error) {
	var input domain.MaterialCheckInput
	if err := json.Unmarshal([]byte(argumentsInJSON), &input); err != nil {
		return "", err
	}
	out, err := t.Runner.Invoke(ctx, input)
	if err != nil {
		return "", err
	}
	b, err := json.Marshal(out)
	if err != nil {
		return "", err
	}
	return string(b), nil
}
